cosmostation/cosmostation-mobile

Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/utils/WDp.java
Cosmos-IOS/Cosmostation/Cosmostation/Base.lproj/Localizable.strings

Typos and tense cleaned up for the mobile app (iOS and Android) version. Fixes should be listed in each individual commit.

Various fixes and typos in cosmostation mobile 

---

Cosmos-Android/app/src/main/res/values/strings.xml
Cosmos-IOS/Cosmostation/Cosmostation/Base.lproj/Localizable.strings
Cosmos-IOS/Cosmostation/Cosmostation/Controller/Main/ko.lproj/MainStoryboard.strings

Random fixes for English language

Fix localization and typos in Android and iOS strings

---

Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/activities/MnemonicCheckActivity.java

Android - chain color of mnemonic screen for IOV

---

Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/activities/MainActivity.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/activities/TxDetailActivity.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/base/BaseActivity.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/base/BaseChain.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/fragment/MainSendFragment.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/network/res/ResLcdKavaAccountInfo.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/task/FetchTask/AccountInfoTask.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/task/FetchTask/UnBondingStateTask.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/utils/WUtil.java
Cosmos-Android/app/src/main/res/values/strings.xml
Cosmos-IOS/Cosmostation/Cosmostation/Base/BaseConstant.swift
Cosmos-IOS/Cosmostation/Cosmostation/Controller/Main/MainTabViewController.swift
Cosmos-IOS/Cosmostation/Cosmostation/Controller/Main/MainTabWalletViewController.swift
Cosmos-IOS/Cosmostation/Cosmostation/Model/KavaAccountInfo.swift
Cosmos-IOS/Cosmostation/Cosmostation/Utils/WUtils.swift

Update Kava Account type with vesting

Support kava-3-test

---

Cosmos-IOS/Cosmostation/Cosmostation/Base/BaseConstant.swift

prepare secret mainnet
https://github.com/cosmostation/cosmostation-mobile/issues/65

iOS - Add secret mainnet end point

---

Cosmos-IOS/Cosmostation/Cosmostation/Base.lproj/Localizable.strings

Update EN localisation

---

Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/activities/ValidatorActivity.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/fragment/MainHistoryFragment.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/task/FetchTask/ApiAccountTxsHistoryTask.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/task/FetchTask/ApiStakeTxsHistoryTask.java
Cosmos-Android/app/src/main/res/values/strings.xml

Android History list and detail for sifchain

---

Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/activities/WebActivity.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/base/BaseConstant.java
Cosmos-Android/app/src/main/res/values/strings.xml

Android Web for sifchain

---

Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/activities/chains/starname/StarNameAccountDetailActivity.java

Android - StarName Crash Bug Fix

Support hyuk sif

---

Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/activities/TxDetailgRPCActivity.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/network/res/ResApiTxListCustom.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/widget/TxUnjailHolder.java

Android - GrpcHistory Unjail list and detail

Android - Grpc Unjail History list and detail add

---

Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/fragment/RedelegateStep1Fragment.java
Cosmos-Android/app/src/main/res/layout/item_redelegate_validator.xml

Android - Redelegate YieldRate Update

---

Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/fragment/DelegateStep2Fragment.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/fragment/ReInvestStep2Fragment.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/fragment/RedelegateStep3Fragment.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/fragment/RewardAddressChangeStep2Fragment.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/fragment/RewardStep2Fragment.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/fragment/SendStep3Fragment.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/fragment/UndelegateStep2Fragment.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/fragment/VoteStep2Fragment.java
Cosmos-Android/app/src/main/res/values-ko/strings.xml
Cosmos-Android/app/src/main/res/values/strings.xml

Andorid - Ki_Gas Point Update

---

Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/activities/TxDetailActivity.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/fragment/chains/ok/DirectVoteFragment0.java

Android - OkStake address for ether style

---

Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/activities/tokenDetail/NativeTokenDetailActivity.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/activities/tokenDetail/StakingTokenDetailActivity.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/dialog/Dialog_Currency_Set.java
Cosmos-Android/app/src/main/res/layout/dialog_currency_set.xml

Android - TokenDetail Addrss ether change and price currency update

---

Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/activities/MainActivity.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/utils/WUtil.java

Support hyuk

---

Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/dialog/Dialog_Currency_Set.java
Cosmos-Android/app/src/main/res/layout/dialog_currency_set.xml

Android - Currecny type restore

---

Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/activities/SendActivity.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/base/BaseConstant.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/fragment/SendStep1Fragment.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/network/res/ResApiTxListCustom.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/utils/WDp.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/utils/WUtil.java
Cosmos-Android/app/src/main/res/values-ko/strings.xml
Cosmos-Android/app/src/main/res/values/strings.xml

Android - bug fix for binance

---

Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/base/BaseActivity.java

Android Bnb available bug fix

---

Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/utils/WUtil.java

Android Akash bug fix

---

Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/base/BaseConstant.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/utils/WUtil.java

Android testnet explorer address add

Android - testnet explorer add for testchain

---

Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/activities/VoteDetailsActivity.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/activities/VoteListActivity.java

Android sercret explorer add

---

Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/dao/ChainParam.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/utils/WDp.java

Support param

---

Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/activities/TxDetailgRPCActivity.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/activities/ValidatorActivity.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/base/BaseChain.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/fragment/MainHistoryFragment.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/network/HistoryApi.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/network/res/ResApiNewTxListCustom.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/task/FetchTask/ApiAccountTxsHistoryTask.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/task/FetchTask/ApiStakeTxsHistoryTask.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/utils/WDp.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/utils/WUtil.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/widget/mainWallet/WalletSifIncentiveHolder.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/widget/txDetail/TxIBCSendHolder.java
Cosmos-Android/app/src/main/res/layout/item_history.xml
Cosmos-Android/app/src/main/res/layout/item_tx_ibc_send.xml
Cosmos-Android/app/src/main/res/values-ko/strings.xml
Cosmos-Android/app/src/main/res/values/strings.xml

Andorid - history for osmosis and incentive for sif

Support hyuk osmosis

---

Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/base/BaseConstant.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/utils/WDp.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/utils/WUtil.java

Android - BaseConstant add for uion

Android - BaseConstant add for uion and hard fix

---

Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/fragment/MainHistoryFragment.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/network/res/ResApiNewTxListCustom.java

Android - history bug fix

---

Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/dao/Account.java

Android - bnb token balance bug fix

Android - bnb token balance bug fix

---

Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/activities/TxDetailActivity.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/activities/TxDetailgRPCActivity.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/base/BaseConstant.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/fragment/MainHistoryFragment.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/widget/txDetail/TxStarnameDeleteAccountHolder.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/widget/txDetail/TxStarnameDeleteDomainHolder.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/widget/txDetail/TxStarnameRegisterAccountHolder.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/widget/txDetail/TxStarnameRegisterDomainHolder.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/widget/txDetail/TxStarnameRenewHolder.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/widget/txDetail/TxStarnameReplaceResourceHolder.java
Cosmos-Android/app/src/main/res/layout/item_tx_starname_renew.xml
Cosmos-Android/app/src/main/res/layout/item_tx_starname_resource.xml

Android - msg typ add for starname

---

Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/base/BaseChain.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/fragment/MainHistoryFragment.java
Cosmos-Android/app/src/main/res/values-ko/strings.xml

Android - bug fix

---

Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/activities/ValidatorActivity.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/fragment/MainHistoryFragment.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/task/FetchTask/ApiAccountTxsHistoryTask.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/task/FetchTask/ApiStakeTxsHistoryTask.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/task/FetchTask/ApiTokenTxsHistoryTask.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/widget/txDetail/osmosis/TxExitPoolHolder.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/widget/txDetail/osmosis/TxJoinPoolHolder.java
Cosmos-Android/app/src/main/res/layout/item_tx_exit_pool.xml
Cosmos-Android/app/src/main/res/layout/item_tx_join_pool.xml
Cosmos-Android/app/src/main/res/values-ko/strings.xml
Cosmos-Android/app/src/main/res/values/strings.xml

Android - pool and iris url chagne

Support hyuk joon

---

Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/base/BaseConstant.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/dao/ChainParam.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/widget/txDetail/osmosis/TxTokenSwapHolder.java

Android - add osmosis param parsing

Android - add osmosis param parsing

---

Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/activities/RestorePathActivity.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/dao/ChainParam.java

Android - restore path bug fix and inflation, apr fix for medi mainnet

---

Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/fragment/SendStep1Fragment.java

Android - sifchain decimal bug fix

Android - sifchain decimal bug fix

---

Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/base/BaseActivity.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/fragment/StepFeeSetFragment.java

Android - bug fix for sifchain

Android - fee set and token list bug fix for sif

---

Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/activities/VoteDetailsActivity.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/dao/ChainParam.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/utils/WUtil.java

Android - vote detail upgrade for certik

---

Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/fragment/chains/rizon/EventHorizonStep0Fragment.java

Android - mnemonic paste bug fix

---

Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/activities/chains/osmosis/EarningDetailActivity.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/activities/chains/osmosis/LabsListActivity.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/dao/ChainParam.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/fragment/chains/osmosis/ListFarmingFragment.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/widget/PoolMyHolder.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/widget/PoolOtherHolder.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/widget/osmosis/EarningMyHolder.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/widget/osmosis/EarningOtherHolder.java

Android - osmosis param update

---

Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/utils/WDp.java

Android - juno chainName bug fix

---

Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/activities/tokenDetail/IBCTokenDetailActivity.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/activities/tokenDetail/NativeTokenGrpcActivity.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/activities/tokenDetail/StakingTokenGrpcActivity.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/base/BaseConstant.java
Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/fragment/chains/ibc/IBCSendStep2Fragment.java

Android - Send amount bug fix

---

Cosmos-Android/app/src/main/java/wannabit/io/cosmostaion/fragment/chains/cosmos/GravitySwapFragment.java

[Android #268] Gdex Swap Rate Decimal Check
